---
title             : "Replication of an Experiment from 'The Comparative Value of Survival Processing'"
shorttitle        : "Adaptive Memory"

author: 
  - name          : "Aira Contreras"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Not Applicable"
    email         : "aira.contreras@gmail.com"

affiliation:
  - id            : "1"
    institution   : "Brooklyn College of the City University of New York"

authornote: |
  This project has been done for Professor Crumps' Spring 2019 Special Topics in Experimental Psychology Pscy. 7709G.

abstract: |
  The experiments in the @nairne2008adaptive paper test human memory systems in survival and non-survival conditions in an effort to determine if one yields measurably better recollection from participants. Participants were asked to rate words in conditions that produce excellent retention including conditions that had words related to pleasantness, imagery, and self reference. Previous experiments have suggested that participants show superior memory when words  were related to survival conditions. The researchers suggest that this may be a result of fitness advantages accrued in the ancestral past. The goal of this exercise is to replicate on of the experiments presented in the [@nairne2008adaptive] paper and determine if the results were similar or even the same. The analysis will be done via the Rstudio software. I was able to [successfully/not successfully] replication the experiment.
  
  
  
  <!-- https://tinyurl.com/ybremelq -->
  
keywords          : "Replication, Adaptive Memory, Survival, Graduate Class"
wordcount         : "X"

bibliography      : ["r-references.bib"]

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf
---

```{r setup, include = FALSE}
library("papaja")
```

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```



# Methods
We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study. <!-- 21-word solution (Simmons, Nelson & Simonsohn, 2012; retrieved from http://ssrn.com/abstract=2160588) -->

## Participants

## Material

## Procedure


## Data analysis
We used `r cite_r("r-references.bib")` for all our analyses.


# Results



# Discussion


\newpage

# References
```{r create_r-references}
r_refs(file = "r-references.bib")

```

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id = "refs"></div>
\endgroup
